# -*- coding: utf-8 -*-
"""Covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/102hqp4Q7vEHFUYJe894Knto-LAmLMbhI
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import pandas as pd
import xlrd
import seaborn as sb
import matplotlib.pyplot as plt

from google.colab import files
from google.colab import drive

drive.mount ('/content/drive')

data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/covid19.csv")

data2=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/covidspread.xlsx")

# capa= tf.keras.layers.Dense(units=1, input_shape=[1])
# modelo = tf.keras.Sequential([capa])

oculta1=tf.keras.layers.Dense(units=3, input_shape=[1])
oculta2=tf.keras.layers.Dense(units=2)
salida=tf.keras.layers.Dense(units=1)
modelo= tf.keras.Sequential([oculta1,oculta2,salida])


oculta1r=tf.keras.layers.Dense(units=50, input_shape=[1])
oculta2r=tf.keras.layers.Dense(units=50)
salidar=tf.keras.layers.Dense(units=1)
modelor= tf.keras.Sequential([oculta1r,oculta2r,salidar])

modelo.compile(
    optimizer = tf.keras.optimizers.Adam(0.05),
    loss='mean_squared_error'
)
modelor.compile(
    optimizer = tf.keras.optimizers.Adam(0.05),
    loss='mean_squared_error'
)

print("Comenzando entrenamiento...")
historial = modelo.fit(data2.num_cases,data2.Muertes,epochs=1000, verbose=False)
historialr = modelor.fit(data2.num_cases,data2.Recuperados,epochs=1000, verbose=False)
print("¡Modelo Entrenado!")

import matplotlib.pyplot as plt
plt.xlabel("# Epoca")
plt.ylabel("Magnitud de perdida")
plt.plot(historial.history["loss"])
plt.plot(historialr.history["loss"])

print("Hagamos una prediccion")
num_casos1=int(input("Ingrese numero de casos: "))
resultado= modelo.predict([num_casos1])
resultador= modelor.predict([num_casos1])
print ("el resultado es " + str(int(resultado)) + " muertes!")
print ("el resultado es " + str(int(resultador)) + " recuperados!")